output_dir = 'output'

[dataset]
name = 'movielens'

[model]
name = 'GiffCF'

n_epochs = 1000
batch_size = 100
test_batch_size = 500
top_k = [10, 20]
monitor = 'val_recall@20'

embed_dim = 200

T = 3
alpha = 1.5
ideal_weight = 0.0
noise_scale = 0.0
noise_decay = 0.5

val_freq = 10
early_stopping = 200
learning_rates = [1e-3, 1e-3]

seed = 0